# NumPy – Numerical Python
## 1. Why Learn NumPy?

#### What is it?

NumPy is a powerful Python library for numerical computations. It provides fast and memory-efficient multi-dimensional arrays.

#### Why we need it?

1.Pure Python lists are slow for large datasets.

2.NumPy arrays are optimized for speed and vectorized operations.

3.Most Data Science & Machine Learning libraries (like Pandas, Scikit-Learn, TensorFlow) are built on top of NumPy.

#### Where is it used?

1.Data Analysis

2.Machine Learning & Deep Learning

3.Image Processing (OpenCV, PIL use NumPy arrays)

5.Scientific Computing & Simulations


#importing the numpy library
import numpy as np

## 2. Importing NumPy
import numpy as np

## 3. Arrays vs Python Lists
import numpy as np
import time

# Python list
py_list = [i for i in range(100000000)]

# NumPy array
np_array = np.arange(100000000)

# Time comparison
start = time.time()
sum(py_list)
print("Python list sum time:", time.time() - start)

start = time.time()
np.sum(np_array)
print("NumPy array sum time:", time.time() - start)


## 4. Creating Arrays
1.np.arange(start, stop, step)

Purpose: Creates an array of numbers starting from start up to but not including stop, incremented by step.

Your code: np.arange(0, 10, 2)

Start = 0

Stop = 10 (exclusive)

Step = 2

2.np.linspace(start, stop, num)

Purpose: Creates an array of num equally spaced numbers between start and stop (inclusive).

Your code: np.linspace(0, 1, 5)

Start = 0

Stop = 1 (inclusive)

5 numbers evenly spaced

# From list 
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# Zeros and Ones
print("Zeros:", np.zeros((2,3)))
print("Ones:", np.ones((2,3)))

# Range and Linspace
print("Arange:", np.arange(0, 10, 2))
print("Linspace:", np.linspace(0, 1, 5))

## 5. Array Properties

arr = np.array([[1,2,3],[4,5,6]])
print("Array shape:", arr.shape)
print("Array dtype:", arr.dtype)
print("Array size:", arr.size)
print("Array ndim:", arr.ndim)

## 6. Indexing and Slicing
arr = np.array([10,20,30,40,50])
print("Element at index 2:", arr[2])
print("Elements from index 1 to 3:", arr[1:4])
print("Elements at indices 0, 2, 4:", arr[[0,2,4]])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])



## Matrix using numpy
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix:\n", matrix)
print("Matrix shape:", matrix.shape)
print("Matrix dtype:", matrix.dtype)
print("Matrix size:", matrix.size)
print("Matrix ndim:", matrix.ndim)
print(matrix[0,1]) # element at row 0, col 1
print(matrix[1,:]) # entire row 1
print(matrix[:,2]) # entire col 2
# Matrix operations
print("Transpose:\n", matrix.T)
print("Sum of all elements:", np.sum(matrix))
print("Sum of each column:", np.sum(matrix, axis=0))
print("Sum of each row:", np.sum(matrix, axis=1))
print("Mean of all elements:", np.mean(matrix))
print("Mean of each column:", np.mean(matrix, axis=0))
print("Mean of each row:", np.mean(matrix, axis=1))
print("Element-wise multiplication:\n", matrix * 2)
print("Matrix multiplication:\n", np.dot(matrix, matrix))  

## 7. Operations and Broadcasting

a = np.array([1,2,3]) 
b = np.array([4,5,6])
print("a + b:", a + b)            # Element-wise addition
print("a * b:", a * b)            # Element-wise multiplication
print("a + 10:", a + 10)          # Broadcasting
print("a * 2:", a * 2)            # Broadcasting

## 8. Mathematical Functions
arr = np.array([1,2,3,4,5])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Square Root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Logarithm:", np.log(arr))

## 9. Reshaping Arrays
arr = np.arange(1, 13)
reshaped = arr.reshape((3,4))
print("Original array:", arr)
print("Reshaped array (3x4):\n", reshaped)
flattened = reshaped.flatten()
print("Flattened array:", flattened)


In [1]:
import numpy as np

import time

# Python list
py_list = [i for i in range(1000000)]

# NumPy array
np_array = np.arange(1000000)

# Time comparison
start = time.time()
sum(py_list)
print("Python list sum time:", time.time() - start)

start = time.time()
np.sum(np_array)
print("NumPy array sum time:", time.time() - start)
print()



Python list sum time: 0.01903057098388672
NumPy array sum time: 0.002337932586669922



In [3]:

print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))


[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [5]:
# From list 
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# Zeros and Ones
print("Zeros:\n", np.zeros((3,3)))
print("Ones:\n", np.ones((3,3)))

# Range and Linspace
print("Arange:", np.arange(3, 30, 3))
print("Linspace:", np.linspace(0, 2, 4))

Array: [1 2 3 4 5]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Arange: [ 3  6  9 12 15 18 21 24 27]
Linspace: [0.         0.66666667 1.33333333 2.        ]


In [21]:
## 5. Array Properties

arr = np.array([[1,2,3],[4,5,6]])
print("Array shape:", arr.shape)
print("Array dtype:", arr.dtype)
print("Array size:", arr.size)
print("Array ndim (1-D, 2-D etc):", arr.ndim)

Array shape: (2, 3)
Array dtype: int32
Array size: 6
Array ndim (1-D, 2-D etc): 2


In [2]:
## 6. Indexing and Slicing
arr = np.array([10,20,30,40,50])
print("Element at index 2:", arr[2])
print("Elements from index 1 to 3:", arr[1:4])
print("Elements at indices 0, 2, 4:", arr[[0,2,4]])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])

## Matrix using numpy
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix:\n", matrix)
print("Matrix shape:", matrix.shape)
print("Matrix dtype:", matrix.dtype)
print("Matrix size:", matrix.size)
print("Matrix ndim:", matrix.ndim)
print(matrix[0,1]) # element at row 0, col 1
print(matrix[1,:]) # entire row 1
print(matrix[:,2]) # entire col 2
# Matrix operations
print("Transpose:\n", matrix.T)
print("Sum of all elements:", np.sum(matrix))
print("Sum of each column:", np.sum(matrix, axis=0))
print("Sum of each row:", np.sum(matrix, axis=1))
print("Mean of all elements:", np.mean(matrix))
print("Mean of each column:", np.mean(matrix, axis=0))
print("Mean of each row:", np.mean(matrix, axis=1))
print("Element-wise multiplication:\n", matrix * 2)
print("Matrix multiplication:\n", np.dot(matrix, matrix))  

Element at index 2: 30
Elements from index 1 to 3: [20 30 40]
Elements at indices 0, 2, 4: [10 30 50]
Every second element: [10 30 50]
Reversed array: [50 40 30 20 10]
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix shape: (3, 3)
Matrix dtype: int64
Matrix size: 9
Matrix ndim: 2
2
[4 5 6]
[3 6 9]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum of all elements: 45
Sum of each column: [12 15 18]
Sum of each row: [ 6 15 24]
Mean of all elements: 5.0
Mean of each column: [4. 5. 6.]
Mean of each row: [2. 5. 8.]
Element-wise multiplication:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Matrix multiplication:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [23]:
## 7. Operations and Broadcasting
a = np.array([1,2,3]) 
b = np.array([4,5,6])
print("a + b:", a + b)            # Element-wise addition
print("a * b:", a * b)            # Element-wise multiplication
print("a + 10:", a + 10)          # Broadcasting
print("a * 2:", a * 2)            # Broadcasting



a + b: [5 7 9]
a * b: [ 4 10 18]
a + 10: [11 12 13]
a * 2: [2 4 6]


In [24]:
## 8. Mathematical Functions
arr = np.array([1,2,3,4,5])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Square Root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Logarithm:", np.log(arr))

Sum: 15
Mean: 3.0
Max: 5
Min: 1
Standard Deviation: 1.4142135623730951
Variance: 2.0
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [25]:
## 9. Reshaping Arrays
arr = np.arange(1, 13)
reshaped = arr.reshape((3,4))
print("Original array:", arr)
print("Reshaped array (3x4):\n", reshaped)
flattened = reshaped.flatten()
print("Flattened array:", flattened)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [38]:
#Create an array 3*3
arr = np.arange(1,10)
print("\nArray\n",arr)

reshaped = arr.reshape((3,3))
print("\n3*3 Matrix(Reshaped):\n",reshaped)
print("\nSecond column:\n",reshaped[:,1])
print("\nSecond row:\n",reshaped[1,:])


Array
 [1 2 3 4 5 6 7 8 9]

3*3 Matrix(Reshaped):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Second column:
 [2 5 8]

Second row:
 [4 5 6]


In [ ]:
#3.Find the mean, median, and standard deviation of [12, 15, 20, 25, 30].
arr = np.array([12, 15, 20, 25, 30])
print("Mean of arr:", np.mean(arr))
print("Median of arr:", np.median(arr))
print("Standard Deviation of arr:", np.std(arr))


In [41]:
# 4.Generate a random 5×5 matrix and find its maximum and minimum values.
# (Hint: Use np.random.rand for random numbers)
import random
mat = np.random.rand(5,5)
print("\nRandom 5x5 Matrix:\n", mat)
print("Maximum value in the matrix:", np.max(mat))
print("Minimum value in the matrix:", np.min(mat))


Random 5x5 Matrix:
 [[0.60032324 0.48899334 0.70485633 0.10457657 0.43997307]
 [0.93734509 0.26345912 0.21300024 0.10155432 0.40732853]
 [0.12605354 0.97651201 0.48736969 0.84287944 0.90421143]
 [0.32481037 0.17315108 0.6511605  0.92581347 0.57350684]
 [0.06154546 0.33426743 0.68385512 0.76860313 0.40848984]]
Maximum value in the matrix: 0.9765120051062186
Minimum value in the matrix: 0.06154545643927978
